# Scaffolding generated by Casein v5.1.1.5

module Casein
  class SidebarsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Sidebars'
  		@sidebars = Sidebar.order(sort_order(:headline)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View sidebar'
      @sidebar = Sidebar.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new sidebar'
    	@sidebar = Sidebar.new
    end

    def create
      @sidebar = Sidebar.new sidebar_params
    
      if @sidebar.save
        flash[:notice] = 'Sidebar created'
        redirect_to casein_sidebars_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new sidebar'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update sidebar'
      
      @sidebar = Sidebar.find params[:id]
    
      if @sidebar.update_attributes sidebar_params
        flash[:notice] = 'Sidebar has been updated'
        redirect_to casein_sidebars_path
      else
        flash.now[:warning] = 'There were problems when trying to update this sidebar'
        render :action => :show
      end
    end
 
    def destroy
      @sidebar = Sidebar.find params[:id]

      @sidebar.destroy
      flash[:notice] = 'Sidebar has been deleted'
      redirect_to casein_sidebars_path
    end
  
    private
      
      def sidebar_params
        params.require(:sidebar).permit(:headline, :info, :image_url, :link)
      end

  end
end