# Scaffolding generated by Casein v5.1.1.5

module Casein
  class WritersController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Writers'
  		@writers = Writer.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View writer'
      @writer = Writer.find params[:id]
    end
  
  end
end